repos:
  - repo: local
    hooks:
      - id: blue
        name: blue
        entry: poetry run blue --check .
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: poetry run ruff check .
        language: system
        types: [python]
